version: 1.0.{build}
image: DESKTOP-T6O32JU
configuration: Release
platform: x64
install:
- cmd: >-
    call olympus/install_dependencies.bat
clone_script:
- cmd: git clone --recursive https://github.com/SleepingSoul/olympus
build:
  project: olympus/olympus/olympus.sln
  parallel: true
  verbosity: normal
build_cloud: DESKTOP-T6O32JU