version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x64
install:
- cmd: >-
    git clone https://github.com/microsoft/vcpkg

    cd vcpkg

    call bootstrap-vcpkg.bat

    vcpkg.exe integrate install

    vcpkg.exe install opengl:x64-windows

    vcpkg.exe install glfw3:x64-windows

    vcpkg.exe install glm:x64-windows

    vcpkg.exe install glad:x64-windows

    vcpkg.exe install stb:x64-windows

    vcpkg.exe install spdlog:x64-windows

    vcpkg.exe install nlohmann-json:x64-windows
    
    vcpkg.exe install imgui:x64-windows
clone_script:
- cmd: git clone --recursive https://github.com/SleepingSoul/olympus c:\projects\olympus
build:
  project: olympus/olympus/olympus.sln
  parallel: true
  verbosity: normal